name: Auto Commit

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show working directory
        run: pwd

      - name: List all files
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run update script
        run: python update.py

      - name: Configure Git
        run: |
          git config user.name "achillesion"
          git config user.email "achillesion@gmail.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto update: $(date)" || echo "No changes to commit"
          git push
